### ISSUE TITLE
Cannot make html

### ISSUE THREAD

**Issue by biglimp** [Urban-Meteorology-Reading/UMEP-Workshop.io#19]
What have been changed?

reading sources... [ 40%] Jupyter/PY1                                 reading sources... [ 42%] Jupyter/PY2                                 reading sources... [ 43%] Jupyter/tutorials/tutorial-1-basic-plotting C:\temp\UMEP-Workshop.io\source\BackGroundMet\BGM1.rst:7: WARNING: Duplicate explicit target name: "manual".
C:\temp\UMEP-Workshop.io\source\BackGroundMet\BGM1.rst:7: WARNING: Duplicate explicit target name: "manual".
C:\temp\UMEP-Workshop.io\source\Jupyter\PY1.rst:8: WARNING: Duplicate explicit target name: "here".

Notebook error:
PandocMissing in Jupyter\tutorials\tutorial-1-basic-plotting.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
http://pandoc.org/installing.html

C:\temp\UMEP-Workshop.io>

**Comment by biglimp** [comment]
Installed Pndoc 2.10 https://github.com/jgm/pandoc/releases/tag/2.10

Still not working...

**Comment by biglimp** [comment]
Fixed for now... Not in my path as they are changed when I set it to be osgeo-specified...

**Comment by sunt05** [comment]
Let’s fix this tomorrow together. 
Basically you need nbsphinx and some dependencies, which are used to display ipynb in a sphinx site.
