### ISSUE TITLE
[Docs]Parameters/tutorials/CP2

### ISSUE THREAD

**Issue by researchConcepts** [Urban-Meteorology-Reading/UMEP-Workshop.io#20]
[page-link](https://github.com/Urban-Meteorology-Reading/UMEP-Workshop.io/blob/master/source/Parameters/tutorials/CP2.rst)

Some files in the example data (runs.zip) do not match their scripting names once unzipped on a case sensitive disk.
For instance, for example 10.3.1.2.1 the following files/directories need to be renamed (or linked):

runs/run/Input -> runs/run/input 
runs/run/Input/Kc_2012_data_60.txt -> runs/run/input/kc_2012_data_60.txt

There might be other issues for other examples (didn't check all of them). I suggest to cross-check that all example file names in the zip files match their names in the example scripts on a case sensitive disk.

**Comment by hamidrezaomidvar** [comment]
Just to clarify, when you unzip the zip files, the files and folders that have uppercase character(originally) will change to lowercase?

**Comment by researchConcepts** [comment]
No, they remain in uppercase. I simply made a symbolic link to their lowercase equivalent.

**Comment by hamidrezaomidvar** [comment]
This is fixed by changing the scripting names in the notebooks.
