### ISSUE TITLE
10.3.1.3. Plot for all sites

### ISSUE THREAD

**Issue by researchConcepts** [Urban-Meteorology-Reading/UMEP-Workshop.io#21]
https://github.com/Urban-Meteorology-Reading/UMEP-Workshop.io/blob/master/source/Parameters/tutorials/CP2.rst

Execution of final command of example 10.3.1.3 leads to an error:

name='US-MMS'
year=2017
LAI_tune(year,name)

Error message for example 10.3.1.3. (Plot for all sites):
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1652             # just raising
   1653             if not (ax.is_categorical() or ax.is_interval()):
-> 1654                 raise KeyError(
   1655                     "Passing list-likes to .loc or [] with any missing labels "
   1656                     "is no longer supported, see "

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

Am I missing something?

**Comment by suegrimmond** [comment]
@hamidrezaomidvar

**Comment by hamidrezaomidvar** [comment]
Thanks for reporting this. I can see that you are using python3.8. Did you follow the steps for creating the appropriate environment (step 2 [here](https://umep-workshop.readthedocs.io/en/latest/Parameters/CalcParam.html))? the version of packages should match in the yml [file](https://github.com/Urban-Meteorology-Reading/SUEWS_parameters/blob/master/environment.yml), otherwise with changes in the packages, you will get to issues.

**Comment by researchConcepts** [comment]
I followed all installation steps for jupyter notebooks but with python and pip based on MacPorts 2.6.2. Didn't run in any issues so far except this one.

**Comment by hamidrezaomidvar** [comment]
I see! can you please let me know what is the version of `pandas` you are using? or give me a report of `pip freeze`

**Comment by researchConcepts** [comment]
pip freeze
appnope==0.1.0
asteval==0.9.18
atmosp==0.2.9
attrs==19.3.0
backcall==0.2.0
bleach==3.1.5
bokeh==2.1.1
cdsapi==0.2.3
certifi==2019.9.11
chardet==3.0.4
click==7.1.2
click-plugins==1.1.1
cligj==0.5.0
cloudpickle==1.5.0
conda==4.3.16
cycler==0.10.0
dask==2.20.0
decorator==4.4.2
defusedxml==0.6.0
distributed==2.20.0
ecmwf-api-client==1.5.4
entrypoints==0.3
f90nml==1.2
Fiona==1.8.13.post1
floweaver==2.0.0a6
fsspec==0.7.4
future==0.18.2
geopandas==0.8.0
HeapDict==1.0.1
idna==2.8
ipykernel==5.3.1
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.1
Jinja2==2.11.2
joblib==0.16.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.5
jupyter-console==6.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
kiwisolver==1.2.0
linecache2==1.0.0
lmfit==1.0.1
locket==0.2.0
lxml==4.5.1
MarkupSafe==1.1.1
matplotlib==3.2.2
mistune==0.8.4
msgpack==1.0.0
munch==2.5.0
nbconvert==5.6.1
nbformat==5.0.7
networkx==2.4
nose==1.3.7
notebook==6.0.3
numexpr==2.7.1
numpy==1.19.0
packaging==20.4
palettable==3.3.0
pandas==1.0.5
pandoc==1.0.2
pandocfilters==1.4.2
parso==0.7.0
partd==1.1.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
Pint==0.14
Platypus-Opt==1.0.4
ply==3.11
prometheus-client==0.8.0
prompt-toolkit==3.0.5
psutil==5.7.0
ptyprocess==0.6.0
pvlib==0.7.2
pycosat==0.6.3
Pygments==2.6.1
pyparsing==2.4.7
pyproj==2.6.1.post1
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.1
qtconsole==4.7.5
QtPy==1.9.0
requests==2.22.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
scikit-learn==0.23.1
scipy==1.5.1
seaborn==0.10.1
Send2Trash==1.5.0
Shapely==1.7.0
six==1.15.0
sortedcontainers==2.2.2
supy==2020.7.8.dev0
supy-driver==2020b1
tables==3.6.1
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl==2.1.0
toolz==0.10.0
tornado==6.0.4
tqdm==4.38.0
traceback2==1.4.0
traitlets==4.3.3
typing-extensions==3.7.4.2
uncertainties==3.1.4
unittest2==1.1.0
urllib3==1.25.7
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
xarray==0.15.1
zict==2.0.0

**Comment by hamidrezaomidvar** [comment]
`pandas` and `supy` are not matching what is required for this tutorial. If you are using `conda`, you can use the `yml` [file](https://github.com/Urban-Meteorology-Reading/SUEWS_parameters/blob/master/environment.yml) referenced in the tutorial. If not, you can make [virtual environment](https://sourabhbajaj.com/mac-setup/Python/virtualenv.html) and downgrade these two packages to match [here](https://github.com/Urban-Meteorology-Reading/SUEWS_parameters/blob/master/environment.yml).. This should fix the problem. Also please update `data.zip` to the latest version.

**Comment by researchConcepts** [comment]
Somehow I can only downgrade pandas and not supy.

virtualenv venv
source venv/bin/activate

pip install pandas==0.25.3
Successfully installed pandas-0.25.3 pytz-2020.1

pip install supy==2019.11.24
ERROR: Could not find a version that satisfies the requirement supy-driver==2019a18 (from supy==2019.11.24) (from versions: 2019b3, 2019b5, 2020a1, 2020a2, 2020a3, 2020a5, 2020a6, 2020a7, 2020a8, 2020a9, 2020a10, 2020b1, 2020b4, 2020b11)
ERROR: No matching distribution found for supy-driver==2019a18 (from supy==2019.11.24)

pip install supy-driver==2019a18
ERROR: Could not find a version that satisfies the requirement supy-driver==2019a18 (from versions: 2019b3, 2019b5, 2020a1, 2020a2, 2020a3, 2020a5, 2020a6, 2020a7, 2020a8, 2020a9, 2020a10, 2020b1, 2020b4, 2020b11)
ERROR: No matching distribution found for supy-driver==2019a18

**Comment by hamidrezaomidvar** [comment]
@sunt05 Have you removed the SuPy versions recently?

**Comment by sunt05** [comment]
> @sunt05 Have you removed the SuPy versions recently?

`2019a18` seems to be there.
A full history can be found here:
https://pypi.org/project/supy-driver/#history

However, note some earlier versions of supy were **NOT** built for later python versions (e.g., >=3.8).

**Comment by hamidrezaomidvar** [comment]
@sunt05 So if you python is <=3.8, it will raise an error during installation?

**Comment by sunt05** [comment]
I assume you meant python >=3.8: then yes, it will because no binary available for python >=3.8

**Comment by sunt05** [comment]
python dependencies are tricky: I would suggest an `env` file defining all dependencies and python version explicitly.

**Comment by researchConcepts** [comment]
Yep, I'd need to downgrade python. No prob to sort it out. Thanks for your help.
