### ISSUE TITLE
guide for installation of jupyter notebooks on Windows

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/UMEP-Workshop.io#7]
@biglimp can you help with this? a short video to guide people to launch jupyter should be fine. I can take over afterwards.

**Comment by sunt05** [comment]
related: https://github.com/Urban-Meteorology-Reading/ViewpointVideos/issues/13

**Comment by biglimp** [comment]
rst formatted text for you to use:

Install Jupyter Notebook on Windows using QGIS/OsGeo Python environment
--------------------------------------------------------------------------------------

**Assumed prior to this**

- `QGIS1`

**Installation**
Jupyter is automatically installed when installing QGIS. To install Notebook:

- In your start menu in Windows, locate **OSGeo4W Shell** and open it. If you automatically do not have administrative rights you need to right-click on **OSGeo4W Shell**, *Open file Location*, Right-click on **OSGeo4W Shell** again and choose *Run as Administrator*.
- type the following two commands:
  ::
                  py3_env
                  pip install notebook
- To start Jupyter Notebook type:
  ::
                  jupyter notebook
